#ifndef _SYNAPTICS_RMI4_H_
#define _SYNAPTICS_RMI4_H_

#define TOUCH_RMI_PAGE_INFO_BYTES 6
#define TOUCH_RMI_PAGE_INFO_ADDRESS 0xE9
#define TOUCH_RMI_MAX_FUNCTIONS 10
#define TOUCH_RMI_F12_FUNCTION  0x12

#define TOUCH_DELAY_TO_COMMUNICATE 200000
#define TOUCH_POWER_RAIL_STABLE_TIME 2000

#define RMI_CHANGE_PAGE_ADDRESS 0xFF

#define TIMER_INTERVAL_TOUCH_POLL 100000
#define TOUCH_BUFFER_SIZE 25
#define TOUCH_DATA_BYTES 8

#define FAILURE_THRESHOLD 25

typedef struct _TOUCH_DATA
{
	UINT16		TouchX;
	UINT16		TouchY;
	UINT8		TouchStatus;
} TOUCH_DATA, *PTOUCH_DATA;

#endif