#ifndef __PCIE_DEFINITION_H__
#define __PCIE_DEFINITION_H__

#define QSERDES_COM_PLL_VCOTAIL_EN 0x004
#define QSERDES_COM_IE_TRIM 0x00C
#define QSERDES_COM_IP_TRIM 0x010
#define QSERDES_COM_PLL_CNTRL 0x014
#define QSERDES_COM_PLL_IP_SETI 0x024
#define QSERDES_COM_PLL_CP_SETI 0x034
#define QSERDES_COM_PLL_IP_SETP 0x038
#define QSERDES_COM_PLL_CP_SETP 0x03C
#define QSERDES_COM_ATB_SEL2 0x044
#define QSERDES_COM_SYSCLK_EN_SEL_TXBAND 0x048
#define QSERDES_COM_RESETSM_CNTRL 0x04C
#define QSERDES_COM_RESETSM_CNTRL2 0x050
#define QSERDES_COM_PLLLOCK_CMP1 0x090
#define QSERDES_COM_PLLLOCK_CMP2 0x094
#define QSERDES_COM_PLLLOCK_CMP_EN 0x09C
#define QSERDES_COM_BGTC 0x0A0
#define QSERDES_COM_DEC_START1 0x0AC
#define QSERDES_COM_SSC_EN_CENTER 0x0B4
#define QSERDES_COM_SSC_ADJ_PER1 0x0B8
#define QSERDES_COM_SSC_PER1 0x0C0
#define QSERDES_COM_RES_CODE_START_SEG1 0x0E0
#define QSERDES_COM_RES_CODE_CAL_CSR 0x0E8
#define QSERDES_COM_RES_TRIM_CONTROL 0x0F0
#define QSERDES_COM_DIV_FRAC_START1 0x100
#define QSERDES_COM_DIV_FRAC_START2 0x104
#define QSERDES_COM_DIV_FRAC_START3 0x108
#define QSERDES_COM_DEC_START2 0x10C
#define QSERDES_COM_PLL_RXTXEPCLK_EN 0x110
#define QSERDES_COM_PLL_CRCTRL 0x114

#define QSERDES_TX_RCV_DETECT_LVL 0x268

#define QSERDES_RX_CDR_CONTROL1 0x400
#define QSERDES_RX_CDR_CONTROL_HALF 0x408
#define QSERDES_RX_UCDR_FO_GAIN 0x414
#define QSERDES_RX_UCDR_SO_GAIN 0x418
#define QSERDES_RX_UCDR_SO_SATURATION_AND_ENABLE 0x41C
#define QSERDES_RX_RX_EQ_GAIN1_LSB 0x4A8
#define QSERDES_RX_RX_EQ_GAIN1_MSB 0x4AC
#define QSERDES_RX_RX_EQ_GAIN2_LSB 0x4B0
#define QSERDES_RX_RX_EQ_GAIN2_MSB 0x4B4
#define QSERDES_RX_RX_EQU_ADAPTOR_CNTRL2 0x4BC
#define QSERDES_RX_RX_EQ_OFFSET_ADAPTOR_CNTRL1 0x4F0
#define QSERDES_RX_RX_OFFSET_ADAPTOR_CNTRL2 0x4F4
#define QSERDES_RX_SIGDET_ENABLES 0x4F8
#define QSERDES_RX_SIGDET_CNTRL 0x500
#define QSERDES_RX_SIGDET_DEGLITCH_CNTRL 0x504

#define PCIE_PHY_SW_RESET 0x600
#define PCIE_PHY_POWER_DOWN_CONTROL 0x604
#define PCIE_PHY_START 0x608
#define PCIE_PHY_ENDPOINT_REFCLK_DRIVE 0x648
#define PCIE_PHY_RX_IDLE_DTCT_CNTRL 0x64C
#define PCIE_PHY_POWER_STATE_CONFIG1 0x650
#define PCIE_PHY_POWER_STATE_CONFIG2 0x654

#define PCIE_PHY_BIST_CHK_ERR_CNT_L 0x718
#define PCIE_PHY_BIST_CHK_ERR_CNT_H 0x71C
#define PCIE_PHY_BIST_CHK_STATUS 0x720
#define PCIE_PHY_LFPS_RXTERM_IRQ_SOURCE 0x724
#define PCIE_PHY_PCS_STATUS 0x728
#define PCIE_PHY_PCS_STATUS2 0x72C
#define PCIE_PHY_REVISION_ID0 0x730
#define PCIE_PHY_REVISION_ID1 0x734
#define PCIE_PHY_REVISION_ID2 0x738
#define PCIE_PHY_REVISION_ID3 0x73C
#define PCIE_PHY_DEBUG_BUS_0_STATUS 0x740
#define PCIE_PHY_DEBUG_BUS_1_STATUS 0x744
#define PCIE_PHY_DEBUG_BUS_2_STATUS 0x748
#define PCIE_PHY_DEBUG_BUS_3_STATUS 0x74C

#define QPHY_FLL_CNTRL1 0xc4
#define QPHY_FLL_CNTRL2 0xc8
#define QPHY_FLL_CNT_VAL_L 0xcc

#define PCIE20_PARF_SYS_CTRL 0x00
#define PCIE20_PARF_PM_STTS 0x24
#define PCIE20_PARF_PCS_DEEMPH 0x34
#define PCIE20_PARF_PCS_SWING 0x38
#define PCIE20_PARF_PHY_CTRL 0x40
#define PCIE20_PARF_PHY_REFCLK 0x4C
#define PCIE20_PARF_CONFIG_BITS 0x50
#define PCIE20_PARF_TEST_BUS 0xE4
#define PCIE20_PARF_DBI_BASE_ADDR 0x168
#define PCIE20_PARF_SLV_ADDR_SPACE_SIZE 0x16C
#define PCIE20_PARF_AXI_MSTR_WR_ADDR_HALT 0x178
#define PCIE20_PARF_LTSSM 0x1B0

#endif